### ISSUE TITLE
Unable to convert JPG images - receive "Bus error: 10" in terminal

### ISSUE THREAD

**Issue by vossavant** [def-/libbpg#2]
I installed bpgenc with Homebrew by typing the following into my terminal:
`brew install libbpg`

I then navigated to a directory containing some images I wanted to convert. I was able to successfully convert PNG images using:
`bpgenc input-file.png -o test.bpg`

However, the same did not work with any `.jpg` or `.jpeg` images:
`bpgenc input-file.jpg -o aaa.bpg`

This yielded **Bus error: 10**. I tried with different images, but only PNG images worked.

Can you tell me what I've done wrong?

**Comment by def-** [comment]
The input formats are probably restricted.

Anyway, this is just a clone of the source code I made to add support for shared libraries: http://bellard.org/bpg/
