### ISSUE TITLE
Windows command line encoder

### ISSUE THREAD

**Issue by degarb** [def-/libbpg#4]
I run a business and create a master weather page, using 60 satellite /map/radar from various universities and government data sources.... Obviously, it is impractical to remotely pull all these in the field over 4g phones that default to 2g, most of the time.

I currently use ImageMagick 7, dos, and autohotkey, to pull, crop, animate, lower resolution, and compress to webp, upload to my weather server.  Autohotkey has zero, nada, Linux equivalent, so after 30 years of using Linux and Unix, I still do not see Linux as a usable operating system for a real power user. (though I don't like the direction windows is going).

Obviously, my dilemma is that I want to use bpg, but believe that there is no dos bpg command line tool compiled for windows.  I am still using 32 bit since I have invested thousands of hours writing programs I still use, which have no equivalent, in 32 bit code and even 16 bit, which ran noticeably faster on 1 and 2 core 32bit machines, at least up to 2007.

**Comment by def-** [comment]
This repo is just an old clone of the source code of libbpg that I used to wrap it in a Nim library.

The original libbpg can be found at https://bellard.org/bpg/

**Comment by degarb** [comment]
It always stunned me that people claimed that linux command line is better than dos, since there was 30 years plus, since 1980, of people writing command line tools for windows.  There are literally 100 thousand plus dos utilities that linux never thought of using. 

The result is tens of thousands of unreplaced 16 bit and 32 bit dos commandline utilities, needed for batch files. 

Thus, why I passed on a 64 bit version of windows.  

This command line on bellard.org is only 64 bit.

Anyone have a 32 bit windows version?
