### ISSUE TITLE
Problem in installation 

### ISSUE THREAD

**Issue by mia-7** [def-/libbpg#5]
Hello,professor！I followed the readme to install, but it meets error in the first step.I need comply it  into video compression and I’m worried about it.

(CYJN) [user058@node05 libbpg-0.9.8]$ make
make -C x265.out/12bit
make[1]: Entering directory /home/user058/CYJ/Open/OpenDVC-master/libbpg-0.9.8/x265.out/12bit' make[1]: *** No targets specified and no makefile found. Stop. make[1]: Leaving directory /home/user058/CYJ/Open/OpenDVC-master/libbpg-0.9.8/x265.out/12bit'
make: *** [x265_make] Error 2

My env is in a Linux server,and non-root directory makes the installation hard.   Hoping you can give me some good solutions as more comprehensive as possible, because I’m a freshman in this aspect.  Thank you for your attention and time.

**Comment by def-** [comment]
This is not the official source of libbpg. Here it is: https://bellard.org/bpg/
